import { Song, SongArtist } from '../shared/types';

export const songs: Song[] = [
  {
    id: 1,
    title: "See You Again",
    artist: "Tyler, the Creator",
    album: "Flower Boy",
    genre: ["Hip Hop", "R&B"],
    release_date: "2017-07-21",
    duration: 197,
    popularity: 1050.4,
  },
  {
    id: 2,
    title: "EARFQUAKE",
    artist: "Tyler, the Creator",
    album: "IGOR",
    genre: ["Hip Hop", "R&B"],
    release_date: "2019-05-17",
    duration: 180,
    popularity: 1150.6,
  },
  {
    id: 3,
    title: "Nights",
    artist: "Frank Ocean",
    album: "Blonde",
    genre: ["R&B", "Soul"],
    release_date: "2016-08-20",
    duration: 306,
    popularity: 1200.8,
  },
  {
    id: 4,
    title: "Ivy",
    artist: "Frank Ocean",
    album: "Blonde",
    genre: ["R&B", "Soul"],
    release_date: "2016-08-20",
    duration: 241,
    popularity: 1100.2,
  },
  {
    id: 5,
    title: "Boredom",
    artist: "Tyler, the Creator",
    album: "Flower Boy",
    genre: ["Hip Hop", "R&B"],
    release_date: "2017-07-21",
    duration: 270,
    popularity: 950.5,
  },
  {
    id: 6,
    title: "Let It Happen",
    artist: "Tame Impala",
    album: "Currents",
    genre: ["Psychedelic Rock", "Pop"],
    release_date: "2015-07-17",
    duration: 463,
    popularity: 1250.3,
  },
  {
    id: 7,
    title: "The Less I Know The Better",
    artist: "Tame Impala",
    album: "Currents",
    genre: ["Psychedelic Rock", "Pop"],
    release_date: "2015-07-17",
    duration: 215,
    popularity: 1300.7,
  },
  {
    id: 8,
    title: "Self Control",
    artist: "Frank Ocean",
    album: "Blonde",
    genre: ["R&B", "Soul"],
    release_date: "2016-08-20",
    duration: 261,
    popularity: 1150.9,
  },
];

export const songArtists: SongArtist[] = [
  {
    songId: 1,
    artistName: "Tyler, the Creator",
    roleName: "Lead Vocalist",
    roleDescription: "Performs lead vocals on 'See You Again'",
  },
  {
    songId: 2,
    artistName: "Tyler, the Creator",
    roleName: "Lead Vocalist",
    roleDescription: "Performs lead vocals on 'EARFQUAKE'",
  },
  {
    songId: 3,
    artistName: "Frank Ocean",
    roleName: "Lead Vocalist",
    roleDescription: "Performs lead vocals on 'Nights'",
  },
  {
    songId: 4,
    artistName: "Frank Ocean",
    roleName: "Lead Vocalist",
    roleDescription: "Performs lead vocals on 'Ivy'",
  },
  {
    songId: 5,
    artistName: "Tyler, the Creator",
    roleName: "Lead Vocalist",
    roleDescription: "Performs lead vocals on 'Boredom'",
  },
  {
    songId: 6,
    artistName: "Kevin Parker",
    roleName: "Lead Vocalist",
    roleDescription: "Performs lead vocals on 'Let It Happen'",
  },
  {
    songId: 7,
    artistName: "Kevin Parker",
    roleName: "Lead Vocalist",
    roleDescription: "Performs lead vocals on 'The Less I Know The Better'",
  },
  {
    songId: 8,
    artistName: "Frank Ocean",
    roleName: "Lead Vocalist",
    roleDescription: "Performs lead vocals on 'Self Control'",
  },
];